name: verify

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip3 install -U git+https://github.com/${{ github.repository }}.git@master


    # required only if you want to verify Haskell code
    - name: Install dependencies (Haskell)
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '8.8.4'
        cabal-version: '3.0.0.0'

    # required only if you want to verify Java code
    - name: Install dependencies (Java)
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'

    # required only if you want to verify C# script files
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.413'
    - name: Install dependencies (C#)
      run: dotnet tool install --global dotnet-script --version 1.3.0

    # required only if you want to verify Go code
    - name: Install dependencies (Go)
      uses: actions/setup-go@v4
      with:
        go-version: '1.20.7'

    # required only if you want to verify Ruby code
    - name: Install dependencies (Ruby)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    # required only if you want to verify Nim code
    - name: Install dependencies (Nim)
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: '1.6.14'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Rust (1.42.0)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.42.0-x86_64-unknown-linux-gnu
        default: true
        profile: minimal

    # required by cargo-udeps
    - name: Set up Rust (nightly)
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-x86_64-unknown-linux-gnu
        default: true
        profile: minimal

    # required only if you set `languages.rust.list_dependencies_backend.kind` to `"cargo-udeps"`
    - name: Install cargo-udeps for Rust
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
        use-tool-cache: true

    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        GH_PAT: ${{ secrets.GH_PAT }}
      run: oj-verify all
